### ISSUE TITLE
error 500

### ISSUE THREAD

**Issue by heyafro** [Michael-Free/Install-Drupal#1]
not sure why, ive tried on a fresh install of ubuntu a few times, i keep getting HTTP error 500 whenever i try to go to the website and try setting it up this is on ubuntu 20.04 
 im getting this error in the apache2 logs i blocked out my ip and website address

[Mon Mar 06 07:39:17.884108 2023] [mpm_prefork:notice] [pid 18882] AH00163: Apache/2.4.41 (Ubuntu) configured -- resuming normal operations
[Mon Mar 06 07:39:17.884272 2023] [core:notice] [pid 18882] AH00094: Command line: '/usr/sbin/apache2'
[Mon Mar 06 07:39:26.701157 2023] [mpm_prefork:notice] [pid 18882] AH00171: Graceful restart requested, doing restart
[Mon Mar 06 07:39:26.894271 2023] [mpm_prefork:notice] [pid 18882] AH00163: Apache/2.4.41 (Ubuntu) configured -- resuming normal operations
[Mon Mar 06 07:39:26.894318 2023] [core:notice] [pid 18882] AH00094: Command line: '/usr/sbin/apache2'
[Mon Mar 06 07:39:55.082397 2023] [php7:error] [pid 19891] [client 180.242*****:14876] PHP Parse error:  syntax error, unexpected 'static' (T_STATIC) in /var/www/****/vendor/symfony/http-foundation/Request.php on line 293
[Mon Mar 06 07:39:57.833696 2023] [php7:error] [pid 19892] [client 180.242.****:10721] PHP Parse error:  syntax error, unexpected 'static' (T_STATIC) in /var/www/******/vendor/symfony/http-foundation/Request.php on line 293

i think thats either an error with drupal itself. or the version of php that the script is installing. 
exit** i think it's installed drupal 10? maybe thats why the rest of the script is probably for drupal 9

**Comment by heyafro** [comment]
i posted a commit with an updated download link, to download the appropriate version of drupal 9, instead of drupal 10

**Comment by Michael-Free** [comment]
Hi there, thanks for the update! i'm currently in the process of updating the script to work with drupal 10 as well.

**Comment by Michael-Free** [comment]
do you have a pull request made?

**Comment by heyafro** [comment]
I think i made a pull request. I could get it installed by changing what
version was used. But couldn't get the website to load anything more than
the home page. The links i went to on the demo pages just show 404. It has
to be something server side but can't figure it out, i don't know Drupal
well.
